import type { GetServerSideProps, NextPage } from "next"
import Head from "next/head"

import Layout from "../components/shared/layout"
import campaign from "../ethereum/campaign"
import factory from "../ethereum/factory"

type Props = {
  campaigns: string[]
}

const Home: NextPage<Props> = ({ campaigns }) => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto min-h-screen max-w-7xl  text-xs text-white">
        <ul role="list" className="space-y-3">
          {campaigns.map((campaign) => (
            <li
              key={campaign}
              className="mx-auto flex w-2/3 items-center justify-between overflow-hidden bg-white py-4 px-4 text-black shadow sm:rounded-md sm:px-6"
            >
              <div className="bg-red-800">
                <p className="w-32 truncate text-sm md:w-full">{campaign}</p>
              </div>

              <button
                type="button"
                className="inline-flex items-center rounded-sm border border-gray-300 bg-white px-6 py-3 text-base font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                See
              </button>
            </li>
          ))}
        </ul>
      </main>
    </Layout>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const campaigns = await factory.methods.getDeployedCampaigns().call()

  const detailledCampaigns = await Promise.all(
    campaigns.map(async (c: any) => {
      const contract = campaign(c)
      return await contract.methods.getSummary().call()
    })
  )

  console.log(campaigns)
  console.log(detailledCampaigns)

  return {
    props: {
      campaigns,
      // array: array && array.map((el) => ({

      // })),
    },
  }
}
