#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn tsc --noEmit && yarn lint . && yarn eslint . && yarn prettier --write .

# Checks prettier format
yarn prettier-check || 
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮.'; 
    false;
)

# Checks Next.js eslint rules
yarn lint || 
(
    echo '😤🏀👋😤 Next.js Eslint rules are not okay! 😤🏀👋😤 ' 
    false;
)

# Checks eslint rules
yarn eslint . --max-warnings 0 || 
(
    echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 '
    false; 
)

# Checks typescript types
yarn check-types || 
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'